"""Updated admission no type in Student model

Revision ID: 4e06e4e6a30d
Revises: 2cf144b65daa
Create Date: 2024-02-09 22:46:27.715029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e06e4e6a30d'
down_revision: Union[str, None] = '2cf144b65daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'admission_no',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'admission_no',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
