"""Models

Revision ID: 60fcb8532c6c
Revises: 7fc0368ec6ad
Create Date: 2024-02-08 14:42:48.189306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fcb8532c6c'
down_revision: Union[str, None] = '7fc0368ec6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=55), nullable=True))
    # op.create_unique_constraint(None, 'students', ['email'])
    # op.create_check_constraint(
    #     "grade_between_1_and_12", 
    #     "students", 
    #     "grade BETWEEN 1 AND 12")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'students', type_='unique')
    # op.drop_constraint('grade_between_1_and_12', 'students')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
